fieldLayouts:
  7ff1f6f7-6e41-4570-8f9b-f48bd53b636f:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: 内容
        sortOrder: 1
handle: homepage
hasTitleField: false
name: Homepage
section: fcab4c87-de82-4368-bac8-4cbb5537a07d
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
